config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root 'jobs#index'
  resources :jobs, only: [:index, :show, :create]
  resources :search, only: [:index]
  resources :events, only: [:index]
end

app/models/job.rb
class Job
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super
  end


  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

   # layout :layout_by_resource



  layout Proc.new { |controller| controller.devise_controller? ? 'devise' : 'application' }

  # def set_new_user
  #   @new_user = User.new
  # end

  # protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :set_new_user

  protected

   def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!, :except => [:index]


  def index
    # Choose the URL to visit
    @app_url = params[:url] || "http://localhost:3000/events"
    # Ensure it starts with http
    @app_url = "http://#{@app_url}" unless @app_url.starts_with?("http")

    begin
      # Retrieve the webpage
      @events = HTTParty.get(@app_url)
    rescue StandardError
      # When something goes wrong create a fallback message
      @events = OpenStruct.new(:code => nil, :message => "Domain not found")
    end
    @event_hash = Hash.new(0)
    @events.each do |event|
      @event_hash[event["job"]] += 1
      @event_hash[event["click"]] += event["click"]
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :click_count, only: [:show]

  def index
    # Choose the URL to visit
    @app_url = params[:url] || "http://localhost:3000/jobs"
    # Ensure it starts with http
    @app_url = "http://#{@app_url}" unless @app_url.starts_with?("http")

    begin
      # Retrieve the webpage
      @jobs = HTTParty.get(@app_url)
    rescue StandardError
      # When something goes wrong create a fallback message
      @jobs = OpenStruct.new(:code => nil, :message => "Domain not found")
    end
  end

  def show
    @app_url = params[:url] || "http://localhost:3000/jobs"
    @jobs = HTTParty.get(@app_url)
    @job = @jobs.find {|job| [job["id"] = params[:id],
                              job["posted"] = params[:posted],
                              job["company"] = params[:company],
                              job["poster"] = params[:poster],
                              job["city"] = params[:city],
                              job["state"] = params[:state],
                              job["title"] = params[:title],
                              job["body"] = params[:body],
                              job["keywords"] = params[:keywords]] }
  end

   def create
    @app_url = params[:url] || "http://localhost:3000/jobs"
    @job = HTTParty.post(@app_url.to_str,
    :body => { :id => params[:id],
               :posted => params[:posted],
               :company => params[:company],
               :poster => params[:poster],
               :city => params[:city],
               :state => params[:state],
               :title => params[:title],
               :body => params[:body],
               :keywords => params[:keywords]
              }.to_json,
    :headers => { 'Content-Type' => 'application/json' } )
    redirect_to :action => :index
  end

  def click_count
    @app_url_events = params[:url] || "http://localhost:3000/events"
    @app_url_jobs = params[:url] || "http://localhost:3000/jobs"
    download = 0
    @jobs = HTTParty.get(@app_url_jobs)
    @job = @jobs.find {|job| [job["id"] = params[:id],
                              job["posted"] = params[:posted],
                              job["company"] = params[:company],
                              job["poster"] = params[:poster],
                              job["city"] = params[:city],
                              job["state"] = params[:state],
                              job["title"] = params[:title],
                              job["body"] = params[:body],
                              job["keywords"] = params[:keywords]] }
    @click = HTTParty.post(@app_url_events.to_str,
    :body => { :job => @job["id"],
               :click => download +=1
              }.to_json,
    :headers => { 'Content-Type' => 'application/json' } )
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @app_url = params[:url] || "http://localhost:3000/jobs"
    @jobs = HTTParty.get(@app_url)
    @search_jobs = @jobs.select {|keyword| keyword["keywords"] == params[:keywords] }
    @job = @jobs.find {|job| job["id"] = params[:id] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<h4 style="text-align: center">Events</h4>

<table align="center" width="750px" border=1 cellpadding=4>
  <tr>
    <th>Id</th>
    <th>Clicks</th>
  </tr>
  <% @event_hash.each do |k,v| %>
  <tr>
    <td><%= k %></td>
    <td><%= v %></td>
  </tr>
  <% end %>
</table>

app/views/jobs/_form.html.erb
<h4 style="text-align: center"> Enter New Job </h4>
<%= form_tag( jobs_path(@job)) do %>
<table align="center" width="750px" border=1 cellpadding=4>
    <tr>
        <td width="25%"><b>Id:</b></td> <td><%= text_field_tag "id", '', size: 75 %></td>
    </tr>
    <tr>
        <td width="25%"><b>Posted:</b></td> <td> <%= text_field_tag "posted", '', size: 75 %></td>
    </tr>
    <tr>
        <td width="25%"><b>Company:</b></td> <td> <%= text_field_tag "company", '', size: 75 %></td>
    </tr>
    <tr>
        <td width="25%"><b>City:</b></td> <td> <%= text_field_tag "city", '', size: 75 %></td>
    </tr>
    <tr>
        <td width="25%"><b>State:</b></td> <td> <%= text_field_tag "state", '', size: 75 %> </td>
    </tr>
    <tr>
        <td width="25%"><b>Title:</b></td> <td> <%= text_field_tag "title", '', size: 75 %> </td>
    </tr>
    <tr>
        <td width="25%"><b>Body:</b></td> <td> <%= text_field_tag "body", '', size: 75 %> </td>
    </tr>
    <tr>
        <td width="25%"><b>Keywords:</b></td> <td> <%= text_field_tag "keywords", '', size: 75 %></td>
    </tr>
    <tr>
        <td width="25%"><b>Click to Submit:</b></td> <td><%= submit_tag 'Submit' %></td>
    </tr>
</table>
<% end %>

app/views/jobs/index.html.erb
<% if user_signed_in? %>
<%= render 'form' %>
<% end %>
<hr>


<% @jobs.each do |job| %>

<table align="center" width="750px" border=1 cellpadding=4>
    <tr>
        <td width="25%"><b>View Job:</b></td> <td><%= link_to 'Click', job_path(job) %></td>
    </tr>
    <tr>
        <td width="25%"><b>Id:</b></td> <td><%= job['id'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Posted:</b></td> <td> <%= job['posted'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Company:</b></td> <td> <%= job['company'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>City:</b></td> <td> <%= job['city'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>State:</b></td> <td> <%= job['state'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Title:</b></td> <td> <%= job['title'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Body:</b></td> <td> <%= job['body'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Keywords:</b></td> <td> <%= job['keywords'] %></td>
    </tr></br>
</table>
<% end %>

app/views/jobs/show.html.erb
<h4 style="text-align: center"><%= @job["title"] %></h4></br>

<table align="center" width="750px" border=1 cellpadding=4>
    <tr>
        <td width="25%"><b>Id:</b></td> <td><%= @job["id"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Posted:</b></td> <td> <%= @job["posted"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Company:</b></td> <td> <%= @job["company"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>City:</b></td> <td> <%= @job["city"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>State:</b></td> <td> <%= @job["state"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Title:</b></td> <td> <%= @job["title"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Body:</b></td> <td> <%= @job["body"] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Keywords:</b></td> <td> <%= @job["keywords"] %></td>
    </tr></br>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Search</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<body>

<div class="navbar">
    <div class="container">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
      <% end %>

      <a href="#" class="brand" > Job Search </a>


        <div class="row">
          <div class="col-sm-1">
            <p><%= link_to "Search", search_index_path %><p>
          </div>
          <div class="col-sm-1">
            <p><%= link_to "Events", events_path %></p>
          </div>
          <div class="col-sm-1">
            <p><%= link_to "All Jobs", jobs_path %></p>
          </div>
        </div>

    </div>
  </div>
<div class="container">
<%= yield %>

</div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Search</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<body class="devise-page">

  <div class="navbar">
    <div class="container">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
      <% end %>



      <a href="#" class="brand" > Job Search </a>
    </br><%= link_to 'Back to Jobs', jobs_path %>
    </div>
  </div>

      <div class="container">
        <p><%= notice %></p>
        <p><%= alert %></p>
        <div class="row">
          <div class="col-sm-3">

          </div>
          </div>
          <div class="col-sm-6">

            <%= yield %>

          </div>
          <div class="col-sm-3">
          </div>
        </div>
      </div>

</body>
</html>

app/views/search/_new.html.erb
<%= form_tag search_index_path, method: :get do %>
<table align="center" width="500px" border=1 cellpadding=4>
    <tr>
      <td><%= text_field_tag :keywords, params[:keywords], size: 75 %></td>
    </tr>
    <tr>
      <td><%= submit_tag "Search", name: nil %></td>
    </tr>
</table>
<% end %>

app/views/search/index.html.erb
<h4 style="text-align: center">Keywords Search</h4>
<%= render "search/new" %></br><hr>

<h4 style="text-align: center"><%= link_to "New Search", search_index_path %></h4>

<% if @search_jobs.nil? %>
<h4 style="text-align: center">No Search Results</h4>
<% else %>
<% @search_jobs.each do |job| %>
<% if job['keywords'].present? %>
<table align="center" width="750px" border=1 cellpadding=4>
    <tr>
        <td width="25%"><b>Id:</b></td> <td><%= job['id'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Posted:</b></td> <td> <%= job['posted'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Company:</b></td> <td> <%= job['company'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>City:</b></td> <td> <%= job['city'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>State:</b></td> <td> <%= job['state'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Title:</b></td> <td> <%= job['title'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Body:</b></td> <td> <%= job['body'] %></td>
    </tr>
    <tr>
        <td width="25%"><b>Keywords:</b></td> <td> <%= job['keywords'] %></td>
    </tr></br>
</table>
<% end %>
<% end %>
<% end %>